version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly

    # Update strategy: allow minor and patch updates
    versioning-strategy: "increase" 
    version-resolver:
      # Only allow minor and patch updates (ignore major releases)
      # Adjust as per your package manager's versioning scheme
      range: ">=0.0.0 <1.0.0" 

    # If tests succeed, automatically merge the updates
    automerge:
      type: "gradual"
